# Generated by scripts/update_homebrew_formula.mjs - do not hand-edit the
# version, url or sha256. Regenerate after every npm release instead:
#   node scripts/update_homebrew_formula.mjs
class UxUiAgentSkills < Formula
  desc "Design-system kit for coding agents: tokens, components, WCAG gates"
  homepage "https://github.com/plugin87/ux-ui-agent-skills"
  url "https://registry.npmjs.org/ux-ui-agent-skills/-/ux-ui-agent-skills-2.9.6.tgz"
  sha256 "321df2cb163c6450d80afc3158f446063d602d380dda22ce38226163a7652e44"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  def caveats
    <<~EOS
      Install the kit into a project:
        cd your-project && ux-ui-skills init

      Pick the agent surface:
        ux-ui-skills init --agent claude   # CLAUDE.md, skills, rules, hooks
        ux-ui-skills init --agent codex    # AGENTS.md (Codex, Cursor, Copilot, Aider)
        ux-ui-skills init --agent both

      The render gates need a browser once per machine:
        npx playwright install chrome
    EOS
  end

  test do
    # The CLI must report the version Homebrew installed. This is the assertion
    # that catches a bottle built from a different tarball than the formula names.
    assert_equal version.to_s, shell_output("#{bin}/ux-ui-skills version").strip

    # init must actually write the surface it promises, and must not write the
    # Claude Code mechanisms on the codex route.
    system bin/"ux-ui-skills", "init", "--agent", "codex"
    assert_path_exists testpath/"AGENTS.md"
    refute_path_exists testpath/"CLAUDE.md"
    refute_path_exists testpath/".claude"

    # The gates are plain Node and Python, so they ship on every route.
    assert_path_exists testpath/"scripts/verify_states.mjs"
    assert_path_exists testpath/"tokens/colors.json"

    # And one browser-free gate must actually run and pass on the kit's own tokens.
    system "python3", testpath/"scripts/validate_tokens.py", testpath/"tokens"
  end
end
